### PR TITLE
Fix a typo in property names

### PR DESCRIPTION
**Pull request by moodmosaic**
I *might* have a bigger PR coming, but I thought I should fix those typos now. (Are they typos? I think so.)

### CODE REVIEW

**Comment by ploeh** [comment]
> I _might_ have a bigger PR coming

Thanks, but if it's too big, I'll be inclined to reject it. This code's main purpose is as an appendix to the blog article, so it has to be in sync with the code shown in the article. Otherwise, I'm concerned that readers will find it less than helpful.

**Comment by moodmosaic** [comment]
Yes, indeed. If I open one (at least, the one I have in mind), it’ll be mostly for discussion.

**Comment by moodmosaic** [comment]
BTW, did you know you can (unorthodoxically?) use just a single library (instead of five different ones) to mix and match property-based tests and inlined test lists? I didn't, so I tried this:

```diff
diff --git a/Problem23.cabal b/Problem23.cabal
index 0a3f842..644e54e 100644
--- a/Problem23.cabal
+++ b/Problem23.cabal
@@ -34,11 +34,7 @@ test-suite Problem23-test
   main-is:             Spec.hs
   build-depends:       base
                      , Problem23
-                     , test-framework
-                     , test-framework-quickcheck2
-                     , test-framework-hunit
-                     , QuickCheck
-                     , HUnit
+                     , hedgehog
                      , random
   ghc-options:         -threaded -rtsopts -with-rtsopts=-N
   default-language:    Haskell2010
diff --git a/test/Spec.hs b/test/Spec.hs
index 2bdf781..6051a84 100644
--- a/test/Spec.hs
+++ b/test/Spec.hs
@@ -1,57 +1,92 @@
-module Main where
+{-# LANGUAGE OverloadedStrings #-}
+module Main (
+    main
+  ) where
 
-import Data.List (genericLength)
-import System.Random
-import Test.Framework (defaultMain, testGroup)
-import Test.Framework.Providers.QuickCheck2 (testProperty)
-import Test.Framework.Providers.HUnit
-import Test.HUnit.Base
-import Test.QuickCheck
-import Lib
+import           Control.Monad  (unless)
+import           Data.List      (genericLength)
+import           Hedgehog
+import qualified Hedgehog.Gen   as Gen
+import qualified Hedgehog.Range as Range
+import           Lib
+import           System.Exit    (exitFailure)
+import           System.IO      (hSetEncoding, stderr, stdout, utf8)
+import           System.Random
 
-lenProp :: Integral i => Int -> [a] -> NonNegative i -> Bool
-lenProp seed xs (NonNegative i) =
-  i == genericLength (rndGenSelect (mkStdGen seed) xs i)
+lenProp g = property $ do
+  seed <- forAll $ Gen.int Range.linearBounded
+  xs   <- forAll g
+  i    <- forAll $ Gen.int $ Range.linear 0 100
+  i === genericLength (rndGenSelect (mkStdGen seed) xs i)
 
-negLenProp :: Integral i => Int -> [a] -> Positive i -> Bool
-negLenProp seed xs (Positive i) =
-  0 == genericLength (rndGenSelect (mkStdGen seed) xs (-i))
+negLenProp g = property $ do
+  seed <- forAll $ Gen.int Range.linearBounded
+  xs   <- forAll g
+  i    <- forAll $ Gen.int $ Range.linear 1 100
+  0 === genericLength (rndGenSelect (mkStdGen seed) xs (-i))
 
 main :: IO ()
-main = defaultMain tests
-
-tests = [
-    testGroup "Properties" [
-      testProperty "rndSelect returns result of correct length" (lenProp :: Int -> [Int] -> N...
-      testProperty "rndSelect returns result of correct length" (lenProp :: Int -> String -> ...
-      testProperty "rndGenSelect returns empty result when count is negative" (negLenProp :: ...
-    ],
-    testGroup "Regression tests" $ hUnitTestToTests $ TestList [
-      "rndGenSelect of chars returns correct result" ~: do
-        (seed, xs, count, expected) <-
-          [
-            (     42,      "foo",  3,        "ofo"),
-            (   1337,      "bar", 10, "rabbaarrra"),
-            (-197221, ['a'..'z'],  5,      "ntfnc")
-          ]
-        let rnd = mkStdGen seed
-
-        let actual = rndGenSelect rnd xs count
-
-        return $ expected ~=? actual
-
-      ,
-      "rndGenSelect of integers returns correct result" ~: do
-        (seed, xs, count, expected) <-
-          [
-            (  19,      [1..3],  3,               [3,1,3]),
-            (1770, [0,1,1,2,7], 10, [1,2,2,1,1,1,1,1,7,7]),
-            ( -19,     [0..99],  5,       [67,48,8,47,42])
-          ]
-        let rnd = mkStdGen seed
-
-        let actual = rndGenSelect rnd xs count
-
-        return $ expected ~=? actual
+main = do
+  hSetEncoding stdout utf8
+  hSetEncoding stderr utf8
+  results <- sequence [
+      properties
+    , regressionTests
     ]
-  ]
+
+  unless (and results)
+    exitFailure
+
+properties :: IO Bool
+properties =
+  checkParallel $ Group "Properties" [
+        ("rndGenSelect returns result of correct length"
+        , lenProp intList)
+      , ("rndGenSelect returns result of correct length"
+        , lenProp strList)
+
+      , ("rndGenSelect returns empty result when count is negative"
+        , negLenProp intList)
+      , ("rndGenSelect returns empty result when count is negative"
+        , negLenProp strList)
+    ]
+  where
+    intList =
+      Gen.list (Range.constant 0 100) $ Gen.int $ Range.linear (-100) 100
+    strList =
+      Gen.list (Range.constant 0 100) $ Gen.alpha
+
+regressionTests :: IO Bool
+regressionTests =
+  checkParallel $ Group "Regression tests" $
+    do
+    (seed, xs, count, expected) <-
+      [
+        (     42,      "foo",  3,        "ofo"),
+        (   1337,      "bar", 10, "rabbaarrra"),
+        (-197221, ['a'..'z'],  5,      "ntfnc")
+      ]
+    let rnd = mkStdGen seed
+
+    let actual = rndGenSelect rnd xs count
+
+    return
+      ("rndGenSelect of chars returns correct result"
+      , withTests 1 . property $ expected === actual)
+
+    ++
+
+    do
+    (seed, xs, count, expected) <-
+      [
+        (  19,      [1..3],  3,               [3,1,3]),
+        (1770, [0,1,1,2,7], 10, [1,2,2,1,1,1,1,1,7,7]),
+        ( -19,     [0..99],  5,       [67,48,8,47,42])
+      ]
+    let rnd = mkStdGen seed
+
+    let actual = rndGenSelect rnd xs count
+
+    return
+      ("rndGenSelect of integers returns correct result"
+      , withTests 1 . property $ expected === actual)
```

If all tests are passing:

image

If a property test fails:

image

If a regression test fails:

image

(FWIW, this is all running on Windows 10.) 

---

And, if you really need to use QuickCheck arbitraries, that's possible as well:

```diff
diff --git a/Problem23.cabal b/Problem23.cabal
index 644e54e..1facc09 100644
--- a/Problem23.cabal
+++ b/Problem23.cabal
@@ -35,6 +35,7 @@ test-suite Problem23-test
   build-depends:       base
                      , Problem23
                      , hedgehog
+                     , hedgehog-quickcheck
                      , random
   ghc-options:         -threaded -rtsopts -with-rtsopts=-N
   default-language:    Haskell2010
diff --git a/test/Spec.hs b/test/Spec.hs
index 6051a84..194c3f3 100644
--- a/test/Spec.hs
+++ b/test/Spec.hs
@@ -7,6 +7,7 @@ import           Control.Monad  (unless)
 import           Data.List      (genericLength)
 import           Hedgehog
 import qualified Hedgehog.Gen   as Gen
+import qualified Hedgehog.Gen.QuickCheck as Gen
 import qualified Hedgehog.Range as Range
 import           Lib
 import           System.Exit    (exitFailure)
@@ -15,13 +16,13 @@ import           System.Random
 
 lenProp g = property $ do
   seed <- forAll $ Gen.int Range.linearBounded
-  xs   <- forAll g
+  xs   <- forAll $ Gen.list (Range.linear 0 100) g
   i    <- forAll $ Gen.int $ Range.linear 0 100
   i === genericLength (rndGenSelect (mkStdGen seed) xs i)
 
 negLenProp g = property $ do
   seed <- forAll $ Gen.int Range.linearBounded
-  xs   <- forAll g
+  xs   <- forAll $ Gen.list (Range.linear 0 100) g
   i    <- forAll $ Gen.int $ Range.linear 1 100
   0 === genericLength (rndGenSelect (mkStdGen seed) xs (-i))
 
@@ -41,20 +42,15 @@ properties :: IO Bool
 properties =
   checkParallel $ Group "Properties" [
         ("rndGenSelect returns result of correct length"
-        , lenProp intList)
+        , lenProp (Gen.arbitrary :: Gen Int))
       , ("rndGenSelect returns result of correct length"
-        , lenProp strList)
+        , lenProp (Gen.arbitrary :: Gen Char))
 
       , ("rndGenSelect returns empty result when count is negative"
-        , negLenProp intList)
+        , negLenProp (Gen.arbitrary :: Gen Int))
       , ("rndGenSelect returns empty result when count is negative"
-        , negLenProp strList)
+        , negLenProp (Gen.arbitrary :: Gen Char))
     ]
-  where
-    intList =
-      Gen.list (Range.constant 0 100) $ Gen.int $ Range.linear (-100) 100
-    strList =
-      Gen.list (Range.constant 0 100) $ Gen.alpha
 
 regressionTests :: IO Bool
 regressionTests =
```

Hope you find this useful. I've pushed this [here](https://github.com/ploeh/HasProblem23/compare/master...moodmosaic:topic/hedgehog) just in case you need it.

**Comment by ploeh** [comment]
Nikos, as you know, I'm sympathetic to the concepts behind Hedgehog, but as you also know [it's too unfriendly on Windows](https://github.com/hedgehogqa/haskell-hedgehog/issues/178) that I consider it something that I currently wish to waste my time on.

**Comment by moodmosaic** [comment]
All you have to do is `:! chcp 65001` inside GHCi if you ever wish to clone and build that branch...

**Comment by ploeh** [comment]
> All you have to do is

No, that's exactly it. That's not all; one also has to apply the `hSetEncoding` hack. And then, as we've discussed in that other issue, `chcp 65001` doesn't actually resolve the issue.

As I said: _unfriendly_

QuickCheck doesn't have those issues.

**Comment by moodmosaic** [comment]
>No, that's exactly it. That's not all

In [this](https://github.com/ploeh/HasProblem23/compare/master...moodmosaic:topic/hedgehog) branch that's *all* you have to do. I know it *sucks*, though. (`:! chcp 65001` inside GHCi)

It's the `hUnitTestToTests`, `~:`, `~=?`, and QuickCheck's arbitrary magic in your code that brought my branch up. Happy to discuss more, if you care.

>QuickCheck doesn't have those issues.

It has *other* issues (or rather, design decisions), though. Not saying Hedgehog is better, we're not actually trying to promote it either. It's just that some people (including myself) find it more convenient than QC.

**Comment by moodmosaic** [comment]
>As I said: *unfriendly* [Haskell Hedgehog on Windows]

FTR, I've opened [a pull request](https://github.com/hedgehogqa/haskell-hedgehog/pull/218) to fix those pesky character encoding issues on Windows. @jystic is currently busy, but I think he will eventually get back and merge it.

**Comment by moodmosaic** [comment]
>FTR, I've opened [a pull request](https://github.com/hedgehogqa/haskell-hedgehog/pull/218) to fix those pesky character encoding issues on Windows. @jystic is currently busy, but I think he will eventually get back and merge it.

FWIW, now merged and just released on Hackage: [Hedgehog 0.6.1](http://hackage.haskell.org/package/hedgehog-0.6.1).

**Comment by ploeh** [comment]
Sounds good. I'll give it a try the next time opportunity arises.

**Comment by moodmosaic** [comment]
OK, and you can still [use QuickCheck generators in Hedgehog](https://github.com/ploeh/HasProblem23/commit/d9699b5a1da551297fa5fada230dd44ebe3cd49d) when you want to.

**Comment by moodmosaic** [comment]
>Sounds good. I'll give it a try the next time opportunity arises.

FWIW, you may have to add `hedgehog >0.6` in your `.cabal` file, as just `hedgehog` might not be enough if you're using an old stack `resolver`.

I came across this today, when I added just `hedgehog` in my `.cabal` file and got `hedgehog 0.5.3` instead of `hedgehog 0.6.1` because I was using an old stack `resolver`.

HTH

**Pull request merged**
